// Hordex report — turns raw findings into something a non-engineer can act on.
// Plain-language "what it means" + "how to fix", grouped by severity, with a
// Markdown export. Also surfaces what changed since the last scan (before-vs-
// after) and what the swarm deliberately avoided (the no-go scope).

const SEV_LABEL = { crit: "Critical", high: "High", med: "Medium", low: "Low" };
const SEV_ORDER = ["crit", "high", "med", "low"];

// Fix guidance for the functional issues the swarm can find.
const FIX_BY_CATEGORY = {
  "JavaScript error": "A code path throws an unhandled error, so the feature just breaks for the user. Reproduce the click, read the console, and guard the failing call.",
  "Server error": "An endpoint returns a 5xx, so the feature fails. Check the server logs for that route and handle the error instead of crashing.",
  "Broken flow": "A form submit is silently failing. Fix the endpoint it posts to (or the payload it sends) and show the user a real success/error state.",
  "Broken link": "A link points at a page that doesn't exist. Fix the href or add the missing route.",
};
export function fixFor(f) {
  return FIX_BY_CATEGORY[f.category] || "Reproduce the issue, confirm the impact, and fix at the source.";
}

export function buildReport(memory, runId, target, prior = { states: 0, findings: 0 }) {
  const findings = memory.findings(runId).map((f) => ({
    severity: f.severity, severityLabel: SEV_LABEL[f.severity] || f.severity,
    type: f.type, category: f.category, title: f.title, url: f.url,
    detail: f.detail, foundBy: f.bot, persona: f.persona,
    newlyBroken: !!f.new_to_origin && (prior.states > 0 || prior.findings > 0),
    fix: fixFor(f),
  }));
  const stats = memory.stats(runId);
  const states = memory.states(runId);
  const skips = memory.skips(runId).map((s) => ({ kind: s.kind, label: s.label, url: s.url, reason: s.reason }));
  const newly = findings.filter((f) => f.newlyBroken);

  return {
    target,
    generatedAt: new Date().toISOString(),
    summary: {
      statesExplored: stats.states,
      findings: stats.findings,
      bySeverity: stats.bySeverity,
      newlyBroken: newly.length,
      skipped: skips.length,
    },
    trainedMemory: prior.states > 0 || prior.findings > 0
      ? { seenBefore: true, priorStates: prior.states, priorFindings: prior.findings,
          newlyBroken: newly.length,
          note: newly.length
            ? `This app was scanned before. ${newly.length} issue${newly.length === 1 ? "" : "s"} here ${newly.length === 1 ? "is" : "are"} new since then — likely broken by a recent change.`
            : "This app was scanned before, and no new issues appeared since then." }
      : { seenBefore: false, note: "First scan of this app — the swarm is learning it now. Re-scan after a change to see what newly broke." },
    findings,
    newlyBroken: newly,
    skipped: skips,
    statesExplored: states.map((s) => ({ url: s.url, title: s.title, firstBot: s.first_bot, visits: s.visits })),
    markdown: toMarkdown(target, findings, stats, skips, newly),
  };
}

export function toMarkdown(target, findings, stats, skips = [], newly = []) {
  const lines = [];
  lines.push(`# Hordex report — ${target}`, "");
  lines.push(`Scanned ${new Date().toLocaleString()} · ${stats.states} pages explored · **${stats.findings} issues found**`, "");
  if (newly.length) lines.push(`> ⚠ ${newly.length} of these are **new since the last scan** — likely broken by a recent change.`, "");
  lines.push(`| Critical | High | Medium | Low |`, `|---|---|---|---|`,
    `| ${stats.bySeverity.crit} | ${stats.bySeverity.high} | ${stats.bySeverity.med} | ${stats.bySeverity.low} |`, "");
  for (const sev of SEV_ORDER) {
    const group = findings.filter((f) => f.severity === sev);
    if (!group.length) continue;
    lines.push(`## ${SEV_LABEL[sev]} (${group.length})`, "");
    for (const f of group) {
      lines.push(`### ${f.title}${f.newlyBroken ? " · 🆕 new since last scan" : ""}`);
      lines.push(`- **Where:** ${f.url || "—"}`);
      if (f.detail) lines.push(`- **What happened:** ${f.detail}`);
      lines.push(`- **How to fix:** ${f.fix}`);
      lines.push(`- **Found by:** ${f.foundBy} (${f.persona})`, "");
    }
  }
  if (skips.length) {
    lines.push(`## Skipped by scope (${skips.length})`, "", "The swarm deliberately avoided these no-go items:", "");
    for (const s of skips) lines.push(`- ${s.label || s.url} — _${s.reason}_`);
    lines.push("");
  }
  lines.push("---", "_Generated by Hordex — the swarm that tests your app before your users do._");
  return lines.join("\n");
}
